name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Download Artifact (arch)
        uses: actions/download-artifact@v4
        with:
          name: wine-tkg-affinity-arch
          path: artifacts/arch
          github-token: ${{ secrets.WORKFLOW_GH_PAT }}

      - name: Rename Artifact (arch)
        run: mv artifacts/arch/wine* artifacts/arch/wine-tkg-affinity-arch.tar

      - name: Compress with xz (arch)
        run: xz artifacts/arch/wine-tkg-affinity-arch.tar

      - name: Download Artifact (fedora)
        uses: actions/download-artifact@v4
        with:
          name: wine-tkg-affinity-fedora
          path: artifacts/fedora
          github-token: ${{ secrets.WORKFLOW_GH_PAT }}

      - name: Rename Artifact (fedora)
        run: mv artifacts/fedora/wine* artifacts/fedora/wine-tkg-affinity-fedora.tar

      - name: Compress with xz (fedora)
        run: xz artifacts/fedora/wine-tkg-affinity-fedora.tar


      # - name: Download Artifact (ubuntu)
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: wine-tkg-affinity-ubuntu
      #     github-token: 

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          files: |
            artifacts/arch/wine-tkg-affinity-arch.tar.xz
            artifacts/arch/wine-tkg-affinity-fedora.tar.xz