name: Wine Ubuntu CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Delete userpatches folder
        run: rm -rf wine-tkg-git/wine-tkg-userpatches
      - uses: actions/checkout@v4
        name: Checkout affinity patches
        with:
          repository: oh-ok/wine-affinity-patches
          path: wine-tkg-git/wine-tkg-userpatches
          sparse-checkout: |
            dxcore.mypatch
            opencl.mypatch
            wintypes.mypatch
          sparse-checkout-cone-mode: false
      - name: Download extra patches
        run: |
          curl https://gitlab.winehq.org/wine/wine/-/merge_requests/6107.patch -o wine-tkg-git/wine-tkg-userpatches/childwindows-vkgl-wayland.mypatch
          curl https://gitlab.winehq.org/wine/wine/-/merge_requests/5573.patch -o wine-tkg-git/wine-tkg-userpatches/childwindows-vkx11.mypatch
          curl https://gitlab.winehq.org/wine/wine/-/merge_requests/6025.patch -o wine-tkg-git/wine-tkg-userpatches/transparent-windows.mypatch
      - name: Cache wine-git
        id: cache-wine-git
        uses: actions/cache@v4
        with:
          path: wine-tkg-git/wine-git
          key: wine-git
      - name: Cache wine-staging-git
        id: cache-wine-staging-git
        uses: actions/cache@v4
        with:
          path: wine-tkg-git/wine-staging-git
          key: wine-staging-git
      - name: Compilation
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          cd wine-tkg-git 
          sed -i 's/distro=""/distro="debuntu"/' customization.cfg
          sed -i 's/_LOCAL_PRESET=""/_LOCAL_PRESET="default-tkg"/' customization.cfg
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          sed -i 's/_PKGNAME_OVERRIDE=""/_PKGNAME_OVERRIDE="affinity"/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-tkg-build
          path: wine-tkg-git/non-makepkg-builds
